version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./:/var/www/current/
    working_dir: /var/www/current
    command: php -S 0.0.0.0:8080 public/index.php
